"""Initial migration

Revision ID: 442291a5fab6
Revises: 
Create Date: 2024-01-02 17:39:51.233698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442291a5fab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mv_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('last_login_on', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('allow_add', sa.Boolean(), nullable=False),
    sa.Column('allow_see_others', sa.Boolean(), nullable=False),
    sa.Column('allow_edit_others', sa.Boolean(), nullable=False),
    sa.Column('allow_delete_others', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_mv_user_id'), ['mv_user_id'], unique=True)

    op.create_table('scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scripts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scripts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scripts_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scripts_name'))
        batch_op.drop_index(batch_op.f('ix_scripts_id'))

    op.drop_table('scripts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mv_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
